trigger: none
pool: genericinfrapool
parameters:
  - name: environment
    displayName: Envrionment
    type: string
    default: dev
    values:
      - dev
      - staging
stages:
  - stage: Terraforminfra
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            commandOptions: '-reconfigure'
            backendServiceArm: 'genericinfras'
            backendAzureRmResourceGroupName: 'rg-todoappproj'
            backendAzureRmStorageAccountName: 'sgtodoapppro'
            backendAzureRmContainerName: 'conttodoapppro'
            backendAzureRmKey: 'dev.terraform.tfstate'
            
        